setup auto deployment

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -21,15 +21,19 @@ jobs:
       - name: Deploy to EC2
         run: |
           ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP_ADDRESS }} << 'EOF'
-            # Update server and install necessary tools
-            sudo apt update -y
-            sudo apt install -y git nodejs npm
+            # Navigate to the root directory
+            cd / || { echo "Failed to navigate to root directory"; exit 1; }
 
-            # Install pm2 globally
-            sudo npm install -g pm2
+            # Check if 'app' directory exists, if not create it
+            if [ ! -d "/app" ]; then
+              echo "'/app' directory does not exist, creating it now."
+              sudo mkdir -p /app
+            else
+              echo "'/app' directory already exists."
+            fi
 
-            # Navigate to the 'app' directory
-            cd /path/to/your/app || { echo "Project directory does not exist"; exit 1; }
+            # Navigate to the '/app' directory
+            cd /app || { echo "Project directory does not exist"; exit 1; }
 
             # Pull the latest changes from the Git repository
             git pull origin main
